# 本文件仅作为实例，请根据实际服务修改此文件内容
apiVersion: v1
kind: Service
metadata:
  {{ if .Values.deploymentStrategy }}
  annotations:
    deploymentStrategy: {{ .Values.deploymentStrategy }}
  {{ end }}
  name: {{ template "service.name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chartName" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
{{toYaml .Values.app.ports | indent 2}}
  selector:
    app: {{ .Values.app.appName }}
    release: {{ .Release.Name }}